version: '3.7'

services:

  elasticsearch:
    image: elasticsearch:7.17.21
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - data_images_elasticsearch:/usr/share/elasticsearch/data

  pgsql:
    image: postgres:15.7
    environment:
      POSTGRES_USER: images
      POSTGRES_PASSWORD: images
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - db_data_imageservice:/var/lib/postgresql/data

  image-service:
    image: sbdi/image-service-dev
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./sbdi/data/config/image-service-config.yml:/data/image-service/config/image-service-config.yml

volumes:
  db_data_imageservice:
#  db_data_imageservice-local:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: "/home/mats/Documents/sbdi/image-service/db_data_image-service__231012"
  data_images_elasticsearch:
