--- 
networks: 
  elasticsearch: ~
services: 
  elasticsearch: 
    container_name: elasticsearch
    environment: 
      - cluster.name=docker-cluster
      - discovery.type=single-node
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.9.2"
    networks: 
      - elasticsearch
    ports: 
      - "9200:9200"
      - "9300:9300"
version: "2"
